import {ICustomerRequest, IDevelopmentService} from "./models.ts";

export const mockDevs: IDevelopmentService[] = [
    {
        uuid: 'jaskdflj;ahfjdlahslj',
        Title: 'Веб-разработка с HTML, CSS и JavaScript',
        Description: 'Создание веб-разработки с использованием HTML, CSS и JavaScript.',
        image_url: 'https://www.miltonmarketing.com/wp-content/uploads/2018/03/codingwebpagemm35353jhep-coursera-course4.png',
        Price: 7896,
        RecordStatus: 0,
        Technology: 'Html, Css, Javascript, React',
        DetailedPrice: 97766,
        ServiceRequest: null,
    },
    {
        uuid: 'sdfdsfsd343',
        Title: 'Python и Django',
        Description: 'Создание веб-сервиса на языке программирования Python и фреймворке Django. Включает в себя работу с базами данных PostgreSQL.',
        image_url: 'https://static18.tgcnt.ru/posts/_0/43/43f7a6914a8de530ef1c3d027fb48508.jpg',
        Price: 5432,
        RecordStatus: 1,
        Technology: 'Python, Django, PostgreSQL',
        DetailedPrice: 65432,
        ServiceRequest: null,
    },
    {
        uuid: 'aklsfdjasdjfklasd',
        Title: 'Java и Spring Boot: Разработка приложений',
        Description: 'Создание приложений на языке Java и фреймворке Spring Boot для создания масштабируемых корпоративных приложений. Работа с базами данных MySQL.',
        image_url: 'https://dengiinterneta.ru/wp-content/uploads/2023/10/kak-pravilno-ustanovit-java-na-sistemu-windows-7.png',
        Price: 12345,
        RecordStatus: 0,
        Technology: 'Java, Spring Boot, MySQL',
        DetailedPrice: 87654,
        ServiceRequest: null,
    },
    {
        uuid: 'dsfasafafdsa',
        Title: 'Frontend-разработка с React.js',
        Description: 'Создание современных пользовательских интерфейсов с использованием библиотеки React.js.',
        image_url: 'https://d1tlrxy0mfxnyo.cloudfront.net/thumbnail/413432/e3662e52-9488-1850-01ae-86114985b2e6.jpg',
        Price: 7896,
        RecordStatus: 0,
        Technology: 'Html, Css, Javascript, React',
        DetailedPrice: 97766,
        ServiceRequest: null,
    },
    {
        uuid: 'jasfk;ljafkdjs;afjh',
        Title: 'Разработка веб-приложений на Flask',
        Description: 'Создание веб-приложения на фреймворке Flask на языке программирования Python.',
        image_url: 'https://scotch-res.cloudinary.com/image/upload/w_auto,q_auto:good,f_auto/media/11238/Fdy7WbU9T123bolKxe2e_poster%20copy.png.jpg',
        Price: 5432,
        RecordStatus: 1,
        Technology: 'Python, Flask, SQLAlchemy',
        DetailedPrice: 65432,
        ServiceRequest: null,
    },
    {
        uuid: 'ghghghg6565',
        Title: 'Бэкенд-разработка с Java и Spring',
        Description: 'Глубокое создание бэкенд-разработки с использованием языка Java и фреймворка Spring. Создание RESTful API и работа с базами данных MySQL.',
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        //@ts-ignore
        image_url: null,
        Price: 12345,
        RecordStatus: 0,
        Technology: 'Java, Spring, MySQL',
        DetailedPrice: 87654,
        ServiceRequest: null,
    },
    {
        uuid: 'uytreewqsd',
        Title: 'Разработка приложений на C# и ASP.NET',
        Description: 'Создание веб-приложения на языке программирования C# и фреймворк ASP.NET. Работа с базой данных SQL Server.',
        image_url: 'https://cdn.dribbble.com/users/1360924/screenshots/6509538/aspnet-core.jpg',
        Price: 9876,
        RecordStatus: 1,
        Technology: 'C#, ASP.NET, SQL Server',
        DetailedPrice: 23456,
        ServiceRequest: null,
    },
    {
        uuid: 'bnmjmjkkj',
        Title: 'Ruby on Rails',
        Description: 'Создание веб-приложения фреймворк Ruby on Rails. Работа с базой данных MongoDB.',
        image_url: 'https://i.pinimg.com/originals/46/97/5a/46975abd4bf6c89aed762173bdfb2e99.jpg',
        Price: 5678,
        RecordStatus: 0,
        Technology: 'Ruby, Ruby on Rails, MongoDB',
        DetailedPrice: 8765,
        ServiceRequest: null,
    },
    {
        uuid: 'iuytrrtyu',
        Title: 'Мобильная разработка на Swift',
        Description: 'Создание мобильных приложений для iOS с использованием языка программирования Swift.',
        image_url: 'https://avatars.dzeninfra.ru/get-zen_doc/5175112/pub_5ee0eafd4121087f382930d5_62e2567fefd3e21b6e6b653f/scale_1200',
        Price: 3456,
        RecordStatus: 1,
        Technology: 'Swift, iOS Development',
        DetailedPrice: 6543,
        ServiceRequest: null,
    },
    {
        uuid: 'xcvbnmbvc',
        Title: 'Разработка веб-приложений с Go',
        Description: 'Создание приложение на языке программирования Go с использованием Google Cloud Platform. Работа с базой данных.',
        image_url: 'https://allineed.ru/images/articles/go/Go-Logo_Blue.png',
        Price: 1234,
        RecordStatus: 0,
        Technology: 'Go, Google Cloud Platform',
        DetailedPrice: 8765,
        ServiceRequest: null,
    },
    {
        uuid: 'mnbvcxzxcv',
        Title: 'Мобильная разработка на Kotlin',
        Description: 'Создание мобильных приложений для Android с использованием языка программирования Kotlin.',
        image_url: 'https://i.pinimg.com/originals/6c/1a/4a/6c1a4a88538ddb1ee6fdea5e7ec8e5e5.png',
        Price: 5678,
        RecordStatus: 1,
        Technology: 'Kotlin, Android Development',
        DetailedPrice: 4321,
        ServiceRequest: null,
    },
    {
        uuid: 'poiuytreww',
        Title: 'Web-разработка с PHP и Laravel',
        Description: 'Создание веб-сервиса с использованием языка программирования PHP и фреймворка Laravel. Взаимодействие с базой данных MySQL.',
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        //@ts-ignore
        image_url: null,
        Price: 9876,
        RecordStatus: 0,
        Technology: 'PHP, Laravel, MySQL',
        DetailedPrice: 12345,
        ServiceRequest: null,
    },
    {
        uuid: 'qazwsxedc',
        Title: 'Full Stack JavaScript: Node.js и MongoDB',
        Description: 'Создание полноценных веб-приложений с использованием JavaScript, Node.js и базы данных MongoDB. Работа с RESTful API и Express.js.',
        image_url: 'https://bymer.ru/wp-content/uploads/2022/12/php-logo.png',
        Price: 5432,
        RecordStatus: 1,
        Technology: 'JavaScript, Node.js, MongoDB',
        DetailedPrice: 23456,
        ServiceRequest: null,
    },
];


export const mockDev: IDevelopmentService = {
    uuid: 'adsfnlkfa;lsdf',
    Title: 'Заголовок 1',
    Description: 'Разработка Frontend для вашего проект',
    image_url: 'https://sun9-74.userapi.com/impg/IkdqPKOIfRr8TF5XrDpx0FApStrqI3N00iDHmw/McWp1do3_sU.jpg?size=1080x1080&quality=95&sign=050a9d0bbcbb22084f2f41f5574b7c71&type=album',
    Price: 7896,
    RecordStatus: 0,
    Technology: 'Html, Css, Javascript, React',
    DetailedPrice: 97766,
    ServiceRequest: null,
}

export const mockCustomerRequests: ICustomerRequest[] = [
    {
        uuid: '6b4296d9-ec50-4bea-89af-5593923e4f53',
        record_status: 3,
        creation_date: '2023-12-04 14:18:56.381764',
        formation_date: '2023-12-04 14:20:19.898110',
        completion_date: '0001-01-01 00:00:00.000000',
        work_specification: 'Сделать крупный проект 1',
        creator: '1d6b2213-f5e5-4eb8-939d-3ab21f60108f',
        moderator: '1d6b2213-f6e7-4eb8-939d-3ab21f60108f',
        development_services: [
            mockDev,
            mockDev,
            mockDev,
        ],
        payment_status: "0",
    },
];

export const mockCustomerRequest: ICustomerRequest = {
    uuid: '6b4296d9-ec50-4bea-89af-5593923e4f53',
    record_status: 3,
    creation_date: '2023-12-04 14:18:56.381764',
    formation_date: '2023-12-04 14:20:19.898110',
    completion_date: '0001-01-01 00:00:00.000000',
    work_specification: 'Сделать крупный проект 1',
    creator: '1d6b2213-f5e5-4eb8-939d-3ab21f60108f',
    moderator: '1d6b2213-f6e7-4eb8-939d-3ab21f60108f',
    development_services: [
        mockDev,
        mockDev,
        mockDev,
    ],
    payment_status: "0",
}
